### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [kusamaxi/chaos-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by hitchho** [comment]
I did add screenshot now, but note out that this is just a custom theme for oh-my-zsh and does not differ that radically from smt.zsh-theme on its own.
